# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "docs"]
  delay = 0
  # 👇 添加这两行，这是解决问题的关键
  poll = true
  poll_interval = 500

[log]
  time = true